name: Auto Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A
      uses: actions/checkout@v2
      with:
        repository: RP-Tama/1TTS-Text-to-Speech-Indonesia
    
    - name: Pull changes from Repo A
      run: git pull

    - name: Checkout Repo B
      uses: actions/checkout@v2
      with:
        repository: Koro129/tes1

    - name: Push changes to Repo B
      run: git push
